[project]
name = "architektury"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "huggingface-hub>=1.1.4",
    "jupyter>=1.1.1",
    "llama-cpp-python>=0.3.16",
]
